### ISSUE TITLE
Breaks in METEOR@1.7.0.3

### ISSUE THREAD

**Issue by jorisroling** [cult-of-coders/grapher-live#16]
I was trying this package in the **grapher-boilerplate** app. That worked will, but after updating that app to **METEOR@1.7.0.3**, it broke with the follwing error.

```javascript
Exception while invoking method 'grapher.live' TypeError: Cannot read property '_id' of null
    at comparator (packages/cultofcoders:grapher/lib/query/hypernova/assembleAggregateResults.js:61:33)
    at _.find.result (packages/cultofcoders:grapher/lib/query/hypernova/assembleAggregateResults.js:68:28)
    at packages/underscore.js:218:20
    at Array.some (<anonymous>)
    at _.some._.any (packages/underscore.js:267:59)
    at Function._.find._.detect (packages/underscore.js:217:5)
    at _.each.aggregateResult (packages/cultofcoders:grapher/lib/query/hypernova/assembleAggregateResults.js:65:34)
    at Function._.each._.forEach (packages/underscore.js:147:22)
    at packages/cultofcoders:grapher/lib/query/hypernova/assembleAggregateResults.js:64:11
    at storeHypernovaResults (packages/cultofcoders:grapher/lib/query/hypernova/storeHypernovaResults.js:59:9)
    at _.each.childCollectionNode (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:9:9)
    at Array.forEach (<anonymous>)
    at Function._.each._.forEach (packages/underscore.js:139:11)
    at hypernova (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:6:7)
    at hypernovaInit (packages/cultofcoders:grapher/lib/query/hypernova/hypernova.js:25:5)
    at Query.fetch (packages/cultofcoders:grapher/lib/query/query.server.js:18:16)
```

**Comment by davidsavoie1** [comment]
Same type of problem here.

```
Cannot read property '0' of undefined
```

Is this package still supported? I really enjoy using Grapher, but a query visualization tool would be very handy.

**Comment by thearabbit** [comment]
+1
